
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc530/src/L1Trigger/L1TGlobal/src/L1TriggerL1TGlobal/a/L1TriggerL1TGlobal_xr.cc_tmp
 "LCGReflex/CorrelationTemplate",
 "LCGReflex/CorrelationTemplate::CorrelationParameter",
 "LCGReflex/std::vector<CorrelationTemplate>",
 "LCGReflex/vector<CorrelationTemplate>",
 "LCGReflex/std::vector<std::vector<CorrelationTemplate> >",
 "LCGReflex/vector<vector<CorrelationTemplate> >",
 "LCGReflex/TriggerMenu",
 "LCGReflex/MuonTemplate",
 "LCGReflex/MuonTemplate::ObjectParameter",
 "LCGReflex/std::vector<MuonTemplate::ObjectParameter>",
 "LCGReflex/vector<MuonTemplate::ObjectParameter>",
 "LCGReflex/MuonTemplate::CorrelationParameter",
 "LCGReflex/std::vector<MuonTemplate>",
 "LCGReflex/vector<MuonTemplate>",
 "LCGReflex/std::vector<std::vector<MuonTemplate> >",
 "LCGReflex/vector<vector<MuonTemplate> >",
 "LCGReflex/CaloTemplate",
 "LCGReflex/CaloTemplate::ObjectParameter",
 "LCGReflex/std::vector<CaloTemplate::ObjectParameter>",
 "LCGReflex/vector<CaloTemplate::ObjectParameter>",
 "LCGReflex/CaloTemplate::CorrelationParameter",
 "LCGReflex/std::vector<CaloTemplate>",
 "LCGReflex/vector<CaloTemplate>",
 "LCGReflex/std::vector<std::vector<CaloTemplate> >",
 "LCGReflex/vector<vector<CaloTemplate> >",
//--End   tmp/slc6_amd64_gcc530/src/L1Trigger/L1TGlobal/src/L1TriggerL1TGlobal/a/L1TriggerL1TGlobal_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
